### ISSUE TITLE
changes for an npm V1 release

### ISSUE THREAD

**Issue by atstp** [CliffCloud/Leaflet.sleep#12]
Picking up from pull request #11  
## readme updates

needed for sure. 
- better overview?
- more detailed use section, perhaps with a copy-pastable example
- the code block at the bottom is ugly

Is there anything that's missing at the moment? 
## config changes

What are the pros of pulling default configs out of the plugin and forcing the user to set them?

I'm hesitant to commit fully to that because then every user needs to add ~10 lines that he or she might not care about. 

@juliengirault thoughts?

**Comment by juliengirault** [comment]
**Re Readme updates:**
You can ignore what I suggested, besides the Config block format if you like it :wink: 

**Re Config changes:**
@atstp I was thinking of putting the default values within `initialize`, so that developers only call `mergeOptions` if they want to override the default values.

I realize though that this is pointless. Developers can easily call `mergeOptions` after including the script on the page, that will override the plugin's default and do the job simply.

Thanks!
