### ISSUE TITLE
Leaflet.Sleep for mobile devices

### ISSUE THREAD

**Issue by Knieper82** [CliffCloud/Leaflet.sleep#7]
Is there an existing EventHandler for mobile devices for touchstart or touchend events?

**Comment by atstp** [comment]
Here are the [events from the leaflet docs](http://leafletjs.com/reference.html#map-events), it might be best to use a non-leaflet event.  

Are there any details you're looking for? does this question relate to L.Sleep?

**Comment by Knieper82** [comment]
yeah your are right. The question not only belongs to L.Sleep but I´m struggling to solve the problem. Tried to include jquery.mobile but that infected the event handling for the whole page. I want a combination of a select button where the user can select a location and the map will pan to it. That all works well for pc but not for mobile devices (Touch-Events) . The select button should only be enabled when the user changes the status in L.Sleep to awake. Any hints?

**Comment by jpcartailler** [comment]
Where is the select button? Is it embedded within L.map or is it outside in the surrounding DOM? Do you have a working example / jsfiddle, perhaps?

**Comment by atstp** [comment]
I'll second c5creative: more info or an example of what you're shooting for would help a lot!

---

here's a blind swing at the issue (to be taken with a grain of salt).

Is something like [L.EasyButton](http://danielmontague.com/projects/easyButton.js/v1/examples/#simple-clicks) what you're shooting for?   It does two of the things you mentioned:
1. lets you click buttons that will center the map accordingly
   - <kbd>£</kbd> centers on the UK
   - <kbd>¥</kbd> centers on Japan
2. because the button is inside the map's container, they'll be un-clickable until the map is awake.

**Comment by atstp** [comment]
looks like this isn't a concern for Leaflet.Sleep  

&nbsp; &nbsp; :runner: :dash: &nbsp; &nbsp;&nbsp;&nbsp;&nbsp; :wrench:
